package AplikasiPenjualan;

import java.sql.Connection; 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JOptionPane;

public class F_Barang extends javax.swing.JFrame {
    DefaultTableModel dtBarang;
    C_Barang cBarang;
    
    public F_Barang() {
        initComponents();
        Tampil_ID();
        Connection conn = koneksi.koneksi.getConnection();
        tfKodeBarang.disable();
        cBarang = new C_Barang();
        setTabel();
    }
    
    public void setTabel(){
        dtBarang = new DefaultTableModel();
        dtBarang.addColumn("KODE BARANG");
        dtBarang.addColumn("NAMA BARANG");
        dtBarang.addColumn("VENDOR BARANG");
        dtBarang.addColumn("STOK BARANG");
        dtBarang.addColumn("HARGA BARANG");
        tblBarang.setModel(dtBarang);
        
        int i=0;
        List <E_Barang> read = cBarang.readData();
        while(i<read.size()){
            dtBarang.addRow(new Object[]{
                read.get(i).kodeBarang,
                read.get(i).namaBarang,
                read.get(i).vendorBarang,
                read.get(i).stokBarang,
                read.get(i).hargaBarang
            });
            i++;
        }
        tblBarang.setModel(dtBarang);
        }
    
    private void clear(){
        tfNamaBarang.setText("");
        tfStokBarang.setText("");
        tfVendorBarang.setText("");
        tfHargaBarang.setText("");
    }
    
    public void Tampil_ID() {
    try {
        Connection conn = koneksi.koneksi.getConnection();
        String sql = "SELECT MAX(RIGHT(kode_barang,6)) AS NO FROM tbl_barang";
        Statement st = conn.createStatement();
        ResultSet rsjual = st.executeQuery(sql);
        while (rsjual.next()) {
            if (rsjual.first() == false) {
                 tfKodeBarang.setText("BR000001");
            } else {
                rsjual.last();
                int auto_id = rsjual.getInt(1) + 1;
                String no = String.valueOf(auto_id);
                int NomorJual = no.length();
                for (int j = 0; j < 6 - NomorJual; j++) {
                    no = "0" + no;
                }
                tfKodeBarang.setText("BR" + no);
            }
        }
        rsjual.close();
        st.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada " +e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbKodeBarang = new javax.swing.JLabel();
        lbNamaBarang = new javax.swing.JLabel();
        lbStokBarang = new javax.swing.JLabel();
        lbHargaBarang = new javax.swing.JLabel();
        tfKodeBarang = new javax.swing.JTextField();
        tfNamaBarang = new javax.swing.JTextField();
        tfVendorBarang = new javax.swing.JTextField();
        tfStokBarang = new javax.swing.JTextField();
        tfHargaBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbVendorBarang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTitle.setText("APLIKASI PENJUALAN TOKO KOMPUTER");
        getContentPane().add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lbKodeBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbKodeBarang.setText("Kode Barang");
        getContentPane().add(lbKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lbNamaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNamaBarang.setText("Nama Barang");
        getContentPane().add(lbNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lbStokBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbStokBarang.setText("Stok Barang");
        getContentPane().add(lbStokBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        lbHargaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHargaBarang.setText("Harga Barang");
        getContentPane().add(lbHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        tfKodeBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodeBarangActionPerformed(evt);
            }
        });
        getContentPane().add(tfKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 240, 30));

        tfNamaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(tfNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 240, 30));

        tfVendorBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tfVendorBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 240, 30));

        tfStokBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStokBarangActionPerformed(evt);
            }
        });
        getContentPane().add(tfStokBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 240, 30));

        tfHargaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaBarangActionPerformed(evt);
            }
        });
        getContentPane().add(tfHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 240, 30));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 874, 210));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 80, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 80, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 90, -1));

        btnClear.setText("Bersihkan");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 90, -1));

        lbVendorBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbVendorBarang.setText("Vendor Barang");
        getContentPane().add(lbVendorBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKodeBarangActionPerformed

    private void tfNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaBarangActionPerformed

    private void tfStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStokBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStokBarangActionPerformed

    private void tfHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaBarangActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String kodeBarang = tfKodeBarang.getText();
        String namaBarang = tfNamaBarang.getText();
        String vendorBarang = tfVendorBarang.getText();
        String stokBarang = tfStokBarang.getText();
        String hargaBarang = tfHargaBarang.getText();
        
        try {
            Connection conn = koneksi.koneksi.getConnection();
            String sql = "INSERT INTO tbl_barang VALUES (?,?,?,?,?)";
            PreparedStatement p = conn.prepareStatement(sql);
            p.setString(1, kodeBarang);
            p.setString(2, namaBarang);
            p.setString(3, vendorBarang);
            p.setString(4, stokBarang);
            p.setString(5, hargaBarang);
            p.executeUpdate();
            p.close();
            
            setTabel();
            clear();
            Tampil_ID();
            
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada " +e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int i = tblBarang.getSelectedRow();
        if (i == -1){
            return;
        }
        
        String kodeBarang = (String) dtBarang.getValueAt(i,0);
        String namaBarang = tfNamaBarang.getText();
        String vendorBarang = tfVendorBarang.getText();
        String stokBarang = tfStokBarang.getText();
        String hargaBarang = tfHargaBarang.getText();
        
        try{
            Connection conn = koneksi.koneksi.getConnection();
            String sql= "UPDATE tbl_barang SET nama_barang = ?, vendor_barang = ?, stok_barang = ?, harga_barang = ? WHERE kode_barang = ?";
            PreparedStatement p = conn.prepareStatement(sql);
            p.setString(5, kodeBarang);
            p.setString(1, namaBarang);
            p.setString(2, vendorBarang);
            p.setString(3, stokBarang);
            p.setString(4, hargaBarang);
            p.executeUpdate();
            p.close();         
            setTabel();
            clear();
            Tampil_ID();

            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada " +e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int i = tblBarang.getSelectedRow();
        if (i == -1){
            return;
        }
        
        String kodeBarang = (String) dtBarang.getValueAt(i,0);
        try{
            Connection conn = koneksi.koneksi.getConnection();
            String sql= "DELETE FROM tbl_barang WHERE kode_barang = ?";
            PreparedStatement p = conn.prepareStatement(sql);
            p.setString(1, kodeBarang);
            p.executeUpdate();
            p.close();         
            setTabel();
            clear();
            Tampil_ID();

            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada " +e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
        Tampil_ID();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int i = tblBarang.getSelectedRow();
        if (i == -1){
            return;
        }
        
        String kodeBarang = (String) dtBarang.getValueAt(i,0);
        tfKodeBarang.setText(kodeBarang);
        
        String namaBarang = (String) dtBarang.getValueAt(i,1);
        tfNamaBarang.setText(namaBarang);
        
        String vendorBarang = (String) dtBarang.getValueAt(i,2);
        tfVendorBarang.setText(vendorBarang);
        
        Integer stokBarang = (Integer) dtBarang.getValueAt(i,3);
        tfStokBarang.setText(String.valueOf(stokBarang));
        
        Integer hargaBarang = (Integer) dtBarang.getValueAt(i,4);
        tfHargaBarang.setText(String.valueOf(hargaBarang));
    }//GEN-LAST:event_tblBarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHargaBarang;
    private javax.swing.JLabel lbKodeBarang;
    private javax.swing.JLabel lbNamaBarang;
    private javax.swing.JLabel lbStokBarang;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbVendorBarang;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField tfHargaBarang;
    private javax.swing.JTextField tfKodeBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfStokBarang;
    private javax.swing.JTextField tfVendorBarang;
    // End of variables declaration//GEN-END:variables
}
