package AplikasiPenjualan;

import java.sql.Connection; 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JOptionPane;

public class F_Pembeli extends javax.swing.JFrame {
    DefaultTableModel dtPembeli;
    C_Pembeli cPembeli;
    
    public F_Pembeli() {
        initComponents();
        Tampil_ID();
        tfIDPembeli.disable();
        Connection conn = koneksi.koneksi.getConnection();
        cPembeli = new C_Pembeli();
        setTabel();
    }
    
    public void setTabel(){
        dtPembeli = new DefaultTableModel();
        dtPembeli.addColumn("ID PEMBELI");
        dtPembeli.addColumn("NAMA PEMBELI");
        dtPembeli.addColumn("NO TELEPON");
        dtPembeli.addColumn("ALAMAT");
        tblPembeli.setModel(dtPembeli);
        
        int i=0;
        List <E_Pembeli> read = cPembeli.readData();
        while(i<read.size()){
            dtPembeli.addRow(new Object[]{
                read.get(i).idPembeli,
                read.get(i).namaPembeli,
                read.get(i).noTelp,
                read.get(i).alaMat
            });
            i++;
        }
        tblPembeli.setModel(dtPembeli);
        }
    
    public void Tampil_ID() {
    try {
        Connection conn = koneksi.koneksi.getConnection();
        String sql = "SELECT MAX(RIGHT(id_pembeli,6)) AS NO FROM tbl_pembeli";
        Statement st = conn.createStatement();
        ResultSet rsjual = st.executeQuery(sql);
        while (rsjual.next()) {
            if (rsjual.first() == false) {
                 tfIDPembeli.setText("KP000001");
            } else {
                rsjual.last();
                int auto_id = rsjual.getInt(1) + 1;
                String no = String.valueOf(auto_id);
                int NomorJual = no.length();
                for (int j = 0; j < 6 - NomorJual; j++) {
                    no = "0" + no;
                }
                tfIDPembeli.setText("KP" + no);
            }
        }
        rsjual.close();
        st.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada " +e);
        }
    }
    
    private void clear(){
        tfNamaPembeli.setText("");
        tfNoTelp.setText("");
        taAlamat.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIdPembeli = new javax.swing.JLabel();
        lbNamaPembeli = new javax.swing.JLabel();
        lbNoTelp = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        tfIDPembeli = new javax.swing.JTextField();
        tfNamaPembeli = new javax.swing.JTextField();
        tfNoTelp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembeli = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIdPembeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbIdPembeli.setText("ID Pembeli");
        getContentPane().add(lbIdPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbNamaPembeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNamaPembeli.setText("Nama Pembeli");
        getContentPane().add(lbNamaPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        lbNoTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNoTelp.setText("No Telepon");
        getContentPane().add(lbNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, -1));

        lbAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbAlamat.setText("Alamat");
        getContentPane().add(lbAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 20));

        tfIDPembeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfIDPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(tfIDPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 280, 30));

        tfNamaPembeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(tfNamaPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 280, 30));

        tfNoTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoTelpActionPerformed(evt);
            }
        });
        getContentPane().add(tfNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 280, 30));

        tblPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembeli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 630, 120));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 80, 30));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 70, 30));

        btnClear.setText("Bersihkan");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 100, 30));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 70, 30));

        taAlamat.setColumns(20);
        taAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        taAlamat.setRows(5);
        jScrollPane2.setViewportView(taAlamat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 390, 140));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI PENJUALAN TOKO KOMPUTER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDPembeliActionPerformed

    private void tfNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoTelpActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String idPembeli = tfIDPembeli.getText();
        String namaPembeli = tfNamaPembeli.getText();
        String noTelp = tfNoTelp.getText();
        String alaMat = taAlamat.getText();
        
        try {
            Connection conn = koneksi.koneksi.getConnection();
            String sql = "INSERT INTO tbl_pembeli VALUES  (?,?,?,?)";
            PreparedStatement p = conn.prepareStatement(sql);
            p.setString(1, idPembeli);
            p.setString(2, namaPembeli);
            p.setString(3, noTelp);
            p.setString(4, alaMat);
            p.executeUpdate();
            p.close();
            setTabel();
            clear();
            Tampil_ID();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Tersimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada " +e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int i = tblPembeli.getSelectedRow();
        if (i == -1){
            return;
        }

        String idPembeli = (String) dtPembeli.getValueAt(i,0);
        String namaPembeli = tfNamaPembeli.getText();
        String noTelp = tfNoTelp.getText();
        String alaMat = taAlamat.getText();
        
        try{
            Connection conn = koneksi.koneksi.getConnection();
            String sql= "UPDATE tbl_pembeli SET nama_pembeli = ?, no_telp = ?, alamat = ? WHERE id_pembeli = ?";
            PreparedStatement p = conn.prepareStatement(sql);
            p.setString(4, idPembeli);
            p.setString(1, namaPembeli);
            p.setString(2, noTelp);
            p.setString(3, alaMat);
            p.executeUpdate();
            p.close();         
            setTabel();
            clear();
            Tampil_ID();

            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada " +e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
        Tampil_ID();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembeliMouseClicked
        // TODO add your handling code here:
        int i = tblPembeli.getSelectedRow();
        if (i == -1){
            return;
        }
        
        String idPembeli = (String) dtPembeli.getValueAt(i,0);
        tfIDPembeli.setText(idPembeli);
        
        String namaPembeli = (String) dtPembeli.getValueAt(i,1);
        tfNamaPembeli.setText(namaPembeli);
        
        String noTelp = (String) dtPembeli.getValueAt(i,2);
        tfNoTelp.setText(noTelp);
        
        String alaMat = (String) dtPembeli.getValueAt(i,3);
        taAlamat.setText(alaMat);
    }//GEN-LAST:event_tblPembeliMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int i = tblPembeli.getSelectedRow();
        if (i == -1){
            return; 
        }
        
        String idPembeli = (String) dtPembeli.getValueAt(i,0);
        try{
            Connection conn = koneksi.koneksi.getConnection();
            String sql= "DELETE FROM tbl_pembeli WHERE id_pembeli = ?";
            PreparedStatement p = conn.prepareStatement(sql);
            p.setString(1, idPembeli);
            p.executeUpdate();
            p.close();         
            setTabel();
            clear();
            Tampil_ID();

            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan pada " +e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Pembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbIdPembeli;
    private javax.swing.JLabel lbNamaPembeli;
    private javax.swing.JLabel lbNoTelp;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTable tblPembeli;
    private javax.swing.JTextField tfIDPembeli;
    private javax.swing.JTextField tfNamaPembeli;
    private javax.swing.JTextField tfNoTelp;
    // End of variables declaration//GEN-END:variables
}
