/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPenjualan;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pradana
 */

public class Form_Barang extends javax.swing.JFrame {
    // Set Variable
     private DefaultTableModel model;
     // String Sesi
     private final String  id_user = Sesi.getId_user_log();
     private final String username = Sesi.getUsername_log();
     private final String password = Sesi.getPassword_log();
    /**
     * Creates new form Form_Barang
     */
    public Form_Barang() {
        initComponents();
        model = new DefaultTableModel();
        // Set Title Table
        tblBarang.setModel(model);
        model.addColumn("Kode Bbarang");
        model.addColumn("Nama Barang");
        model.addColumn("Vendor Barang");
        model.addColumn("Stok Barang");
        model.addColumn("Harga Barang");
        // Load Method
        loadData();
        kode();
        
       
    }
     
    // Method Blokir Huruf Pada Twxt Field
    public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "Masukkan Angka Saja!!!", "Pesan", JOptionPane.WARNING_MESSAGE);
       }
    }
    
    // Method Menampilkan Data Ke Table
    public final void loadData() {
        // Enable Dan Disable Beberapa Button
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(false);
        btnEdit.setEnabled(false);
        tfKodeBarang.setEnabled(false);
        // Mendapatkan Data
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            //Koneksi Ke Database
            Connection c = koneksi.getKoneksi();
            // Kueri Menampilkan Table Barang
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbl_barang";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                // Menampilkan Data Table Ke Baris Kolom
                Object[] o = new Object[5];
                o[0] = r.getString("kode_barang");
                o[1] = r.getString("nama_barang");
                o[2] = r.getString("vendor_barang");
                o[3] = r.getString("stok_barang");
                o[4] = r.getString("harga_barang");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // Method Membuat Kode Barang Secara Beraturan
    private void kode() {
        try {
            // Koneksi Ke Database
            Connection c = koneksi.getKoneksi();
            // Kueri Menampilkan Kode Barang Di Table Barang
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbl_barang ORDER BY kode_barang DESC";
            ResultSet r = s.executeQuery(sql);
            // Validasi Cek Nomor Secara Beraturan
            if (r.next()) {
                String noKode = r.getString("kode_barang");
                String AN = "" + (Integer.parseInt(noKode) + 1);
                tfKodeBarang.setText(AN);
            } else {
                tfKodeBarang.setText("1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
    // Method Untuk Membersihkan Form
    private void Clear(){
        kode();
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        tfNamaBarang.setText("");
        tfVendorBarang.setText("");
        tfStokBarang.setText("");
        tfHargaBarang.setText("");
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCariBarang = new javax.swing.JLabel();
        lbKodeBarang = new javax.swing.JLabel();
        lbNamaBarang = new javax.swing.JLabel();
        lbVendorBarang = new javax.swing.JLabel();
        lbJumlahBarang = new javax.swing.JLabel();
        tfKodeBarang = new javax.swing.JTextField();
        tfVendorBarang = new javax.swing.JTextField();
        tfNamaBarang = new javax.swing.JTextField();
        tfStokBarang = new javax.swing.JTextField();
        tfHargaBarang = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tfCari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCariBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCariBarang.setText("Cari");
        jPanel1.add(lbCariBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        lbKodeBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbKodeBarang.setText("Kode Barang");
        jPanel1.add(lbKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbNamaBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNamaBarang.setText("Nama Barang");
        jPanel1.add(lbNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lbVendorBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVendorBarang.setText("Vendor Barang");
        jPanel1.add(lbVendorBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lbJumlahBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbJumlahBarang.setText("Stok Barang");
        jPanel1.add(lbJumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        tfKodeBarang.setEditable(false);
        jPanel1.add(tfKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, 30));
        jPanel1.add(tfVendorBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, 30));
        jPanel1.add(tfNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 230, 30));

        tfStokBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfStokBarangKeyTyped(evt);
            }
        });
        jPanel1.add(tfStokBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 230, 30));

        tfHargaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfHargaBarangKeyTyped(evt);
            }
        });
        jPanel1.add(tfHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 230, 30));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 100, 30));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 100, 30));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 100, 30));

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 770, 180));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Harga Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        tfCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCariKeyReleased(evt);
            }
        });
        jPanel1.add(tfCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 270, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("APLIKASI PENJUALAN TOKO KOMPUTER");
        jPanel2.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 70, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method Untuk Kembali Ke Form Menu
    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        Form_Menu fb = new Form_Menu();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    // Method Untuk Menambahkan Data
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        // Validasi Data Biar Tidak Kosong
        if(tfKodeBarang.getText().equals("") ||tfNamaBarang.getText().equals("") ||tfVendorBarang.getText().equals("") ||tfStokBarang.getText().equals("") ||tfHargaBarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data||!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }else{
            // Menyimpan String Dari Text Field
            String kbarang = tfKodeBarang.getText();
            String nbarang = tfNamaBarang.getText();
            String vbarang = tfVendorBarang.getText();
            String sbarang = tfStokBarang.getText();
            String hbarang = tfHargaBarang.getText();
           
            try {
                // Mengambil Data Waktu Sekarang
                long millis=System.currentTimeMillis();  
                java.sql.Date date=new java.sql.Date(millis);  
                System.out.println(date); 
                String tgl = date.toString();
                // Koneksi Ke Database
                Connection c = koneksi.getKoneksi();
                // Kueri Untuk Menambahkan Data
                String sql = "INSERT INTO tbl_barang VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, kbarang);
                p.setString(2, nbarang);
                p.setString(3, vbarang);
                p.setString(4, sbarang);
                p.setString(5, hbarang);
                p.setString(6, tgl);
                // Mengambil ID User dari Sesi
                p.setString(7, id_user);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                loadData();
                Clear();
                kode();
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    // Event Table Jika Di Klik
    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        // Enable dan Disable Beberapa Button
        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        // Seleksi Data Berdasarkan Kolom Table
        int i = tblBarang.getSelectedRow();
        if (i == -1) {
            return;
        }
        // Menambahkan Text Ke Kode Barang Text Field
        String kbarang = (String) model.getValueAt(i, 0);
        tfKodeBarang.setText(kbarang);
        tfKodeBarang.setEnabled(false);

        // Menambahkan Text Ke Nama Barang Text Field
        String nbarang = (String) model.getValueAt(i, 1);
        tfNamaBarang.setText(nbarang);

        // Menambahkan Text Ke Vendor Barang Text Field
        String vbarang = (String) model.getValueAt(i, 2);
        tfVendorBarang.setText(vbarang);
        
        // Menambahkan Text Ke Stok Barang Text Field
        String sbarang = (String) model.getValueAt(i, 3);
        tfStokBarang.setText(sbarang);

        // Menambahkan Text Ke Harga Barang Text Field
        String hbarang = (String) model.getValueAt(i, 4);
        tfHargaBarang.setText(hbarang);
    }//GEN-LAST:event_tblBarangMouseClicked

    // Method Untuk Menghapus Data
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // Validasi Data Biar Tidak Kosong
         try {
             // Koneksi Ke Database
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            // Kueri Untuk Mneghapus Data
            String sql ="DELETE FROM tbl_barang WHERE kode_barang ='"+tfKodeBarang.getText()+"'";
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        loadData();
        Clear();
        kode();
    }//GEN-LAST:event_btnHapusActionPerformed

    // Method Untuk Mengubah Data
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        // Validasi Data Biar Tidak Kosong
        if(tfKodeBarang.getText().equals("") ||tfNamaBarang.getText().equals("") ||tfVendorBarang.getText().equals("") ||tfStokBarang.getText().equals("") ||tfHargaBarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data||!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }else{
        // Seleksi Data JIKa Kolom Table Dipilih
        int i = tblBarang.getSelectedRow();
        if (i == -1) {
            return;
        }
        // Menyimpan String Dari Kolom Table
        String user = (String) model.getValueAt(i, 0);
        try {
            // Koneksi Ke Database
            Connection c = koneksi.getKoneksi();
            // Kueri Untuk Menambahkan Data
            String sql = "UPDATE  tbl_barang SET nama_barang =  '" + tfNamaBarang.getText() + "', vendor_barang='"+ tfVendorBarang.getText() + "', stok_barang='"+ tfStokBarang.getText() + "', harga_barang='"+ tfHargaBarang.getText() +"' WHERE  kode_barang ='" + tfKodeBarang.getText() + "'";
            PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            loadData();
            Clear();
            kode();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah", "pesan", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    // Method Untuk mencari Data
    private void tfCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCariKeyReleased
        // TODO add your handling code here:
        // Mendapatkan Data
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            // Koneksi Ke Database
            Connection c = koneksi.getKoneksi();
            // Kueri Memilih Table
            Statement s = c.createStatement();
            String sql = "select * from tbl_barang where kode_barang like '%" + tfCari.getText() + "%' or nama_barang like'%" + tfCari.getText() + "%' or vendor_barang like'" + tfCari.getText() + "%' or stok_barang like'%" + tfCari.getText() + "%' " + "or harga_barang like'%" + tfCari.getText() + "%'";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                // Menampilkan Data Table Ke Baris Kolom
                Object[] o = new Object[5];
                o[0] = r.getString("kode_barang");
                o[1] = r.getString("nama_barang");
                o[2] = r.getString("vendor_barang");
                o[3] = r.getString("stok_barang");
                o[4] = r.getString("harga_barang");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tfCariKeyReleased

    // Blokir Huruf Pada Text Field Stok Barang
    private void tfStokBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStokBarangKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
        
    }//GEN-LAST:event_tfStokBarangKeyTyped

    // Blokir Huruf Pada Text Field Harga Barang
    private void tfHargaBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHargaBarangKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_tfHargaBarangKeyTyped

    // Method Untuk Membersihkan Data
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCariBarang;
    private javax.swing.JLabel lbJumlahBarang;
    private javax.swing.JLabel lbKodeBarang;
    private javax.swing.JLabel lbNamaBarang;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbVendorBarang;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfHargaBarang;
    private javax.swing.JTextField tfKodeBarang;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfStokBarang;
    private javax.swing.JTextField tfVendorBarang;
    // End of variables declaration//GEN-END:variables
}
