/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPenjualan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pradana
 */

public class Form_Admin extends javax.swing.JFrame {
    // Set Variable
    private DefaultTableModel model;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form Form_Admin
     */
    public Form_Admin() {
        initComponents();
        model = new DefaultTableModel();
        // Set Title Table
        tblAdmin.setModel(model);
        model.addColumn("ID User");
        model.addColumn("Username");
        model.addColumn("Nama Lengkap");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No Telp");
        model.addColumn("Alamat");
        // Load Method
        id();
        loadData();
    }
    
    // Method Menampilkan Data Ke Table
    public void loadData() {
        // Enable dan Disable Beberapa Button
        btnTambah.setEnabled(true);
        btnHapus.setEnabled(false);
        btnUbah.setEnabled(false);
        tfUsername.setEnabled(true);
        // Mendapatkan Data
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            // Koneksi Ke Database
            Connection c = koneksi.getKoneksi();
            // Kueri Menampilkan Table 
            Statement s = c.createStatement();
            String sql = "SELECT * FROM tbl_admin";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                // Menampilkan Data Table Ke Baris Kolom
                Object[] o = new Object[7];
                o[0] = r.getString("id_user");
                o[1] = r.getString("username");
                o[2] = r.getString("nama_lengkap");
                o[3] = r.getString("jenis_kelamin");
                o[4] = r.getString("no_telp");
                o[5] = r.getString("alamat");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    // Method Membuat ID Secara Beraturan
    private void id() {
        // Disable Button ID User
        tfIdUser.setEnabled(false);
        try {
            // Koneksi Ke Database
            Connection c = koneksi.getKoneksi();
            // Kueri Menampilkan ID User di Table Admin
            st = c.createStatement();
            String iduser = "SELECT * FROM tbl_admin ORDER by id_user desc";
            rs = st.executeQuery(iduser);
            // Validasi Cek Nomor Secara Beraturan
            if (rs.next()) {
                String noid = rs.getString("id_user");
                String AN = "" + (Integer.parseInt(noid) + 1);
                tfIdUser.setText(AN);
            } else {
                tfIdUser.setText("1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }  
    } 
    
    // Method Menampilkan Data Password Table Admin 
    private void EdtPassword(){
        // Mendapatkan Text Field ID User Untuk Seleksi Password
        String iduser = tfIdUser.getText();
        try {
            // Koneksi Ke Database
            Connection c = koneksi.getKoneksi();
            // Kueri Memilih Password Berdasarkan ID User Yang Dipilih
            st = c.createStatement();
            String edt_pass = "SELECT password FROM tbl_admin WHERE id_user = '" + iduser + "'";
            rs = st.executeQuery(edt_pass);
            // Mendapatkan Data Password Ke Text Field
            if (rs.next()) {
                String pass = rs.getString("password");
                pfPassword.setText(pass);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    // Method Untuk Membersihkan Form
    private void Clear(){
        id();
        btnTambah.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        tfUsername.setText("");
        pfPassword.setText("");
        tfNamaLengkap.setText("");
        bgClear.clearSelection();
        tfNoTelp.setText("");
        taAlamat.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgClear = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbIdUser = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbJenisKelamin = new javax.swing.JLabel();
        lbNamaLengkap = new javax.swing.JLabel();
        lbNoTelp = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        tfIdUser = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        tfNamaLengkap = new javax.swing.JTextField();
        rbLakiLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        tfNoTelp = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIdUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIdUser.setText("ID User");
        jPanel1.add(lbIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUsername.setText("Username   ");
        jPanel1.add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, -1));

        lbPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPassword.setText("Password    ");
        jPanel1.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lbJenisKelamin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbJenisKelamin.setText("Jenis Kelamin   ");
        jPanel1.add(lbJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, -1));

        lbNamaLengkap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNamaLengkap.setText("Nama Lengkap");
        jPanel1.add(lbNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));

        lbNoTelp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNoTelp.setText("No. Telp  ");
        jPanel1.add(lbNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 100, -1));

        lbAlamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbAlamat.setText("Alamat  ");
        jPanel1.add(lbAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 100, -1));
        jPanel1.add(tfIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 170, 30));
        jPanel1.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 170, 30));
        jPanel1.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 170, 30));
        jPanel1.add(tfNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 170, 30));

        bgClear.add(rbLakiLaki);
        rbLakiLaki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbLakiLaki.setText("Laki-Laki");
        jPanel1.add(rbLakiLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        bgClear.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPerempuan.setText("Perempuan");
        jPanel1.add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
        jPanel1.add(tfNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 170, 30));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, 40));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 90, 40));

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 100, 40));

        jTextField4.setText("jTextField3");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 170, 30));

        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdmin);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 770, 150));

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane2.setViewportView(taAlamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 170, 100));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("APLIKASI PENJUALAN TOKO KOMPUTER");
        jPanel2.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, 30));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method Untuk Menghapus Data
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // Validasi Data Biar Tidak Kosong
        if(tfIdUser.getText().equals("") || tfUsername.getText().equals("") ||pfPassword.getText().equals("")|| tfNamaLengkap.getText().equals("")|| rbLakiLaki.getText().equals("")|| tfNoTelp.getText().equals("")|| taAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data!!!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }else{
        try {
            // Koneksi Ke Database
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            // Kueri Untuk Mneghapus Data
            String sql ="DELETE FROM tbl_admin WHERE id_user='"+tfIdUser.getText()+"'";
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        loadData();
        Clear();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    // Method Untuk Menambahkan Data
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        // Validasi Data Biar Tidak Kosong
        if(tfIdUser.getText().equals("") || tfUsername.getText().equals("") ||pfPassword.getText().equals("")|| tfNamaLengkap.getText().equals("")|| rbLakiLaki.getText().equals("")|| tfNoTelp.getText().equals("")|| taAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data!!!", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }else{
            // Menyimpan String Dari Text Field
            String id = tfIdUser.getText();
            String user = tfUsername.getText();
            String pass = pfPassword.getText();
            String namaa = tfNamaLengkap.getText();
            String notelpp = tfNoTelp.getText();
            String alamatt = taAlamat.getText();
            String jk ="";
            if(rbLakiLaki.isSelected()){
                jk = rbLakiLaki.getText();
            }else{
                jk = rbPerempuan.getText();
            }
            try {
                // Koneksi Ke Database
                Connection c = koneksi.getKoneksi();
                // Kueri Untuk Menambahkan Data
                String sql = "INSERT INTO tbl_admin VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id);
                p.setString(2, user);
                p.setString(3, pass);
                p.setString(4, namaa);
                p.setString(5, jk);
                p.setString(6, notelpp);
                p.setString(7, alamatt);
                p.executeUpdate();
                p.close();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                loadData();
                Clear();
                id();
                JOptionPane.showMessageDialog(null, "Data Berhasil Tersimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnTambahActionPerformed

    // Method Untuk Mengubah Data
    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        // Seleksi Data Jika Kolom Table Dipilih
        int i = tblAdmin.getSelectedRow();
        if (i == -1) {
            return;
        }
        // ID User dari Kolom Table
        String user = (String) model.getValueAt(i, 0);
        try {
            // Koneksi Ke Database
            Connection c = koneksi.getKoneksi();
            String jk ="";
            if(rbLakiLaki.isSelected()){
                jk = rbLakiLaki.getText();
            }else{
                jk = rbPerempuan.getText();
            }
            // Kueri Untuk Mengubah Data
            String sql = "UPDATE  tbl_admin SET username = '" + tfUsername.getText() +"', password =  '" + pfPassword.getText() + "', nama_lengkap = '" + tfNamaLengkap.getText() + "', jenis_kelamin='"+ jk +"', no_telp = '" + tfNoTelp .getText() + "', alamat = '" + taAlamat.getText() + "' WHERE  id_user ='" + tfIdUser.getText() + "'";
            PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            loadData();
            Clear();
            id();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUbahActionPerformed

    // Event Table Jika Di Klik
    private void tblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminMouseClicked
        // TODO add your handling code here:
        // Enable dan Disable Beberapa Button
        btnTambah.setEnabled(false);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
        // Seleksi Data Berdasarkan Kolom Table
        int i = tblAdmin.getSelectedRow();
        if (i == -1) {
            return;
        }
        // Menambahkan Text Ke ID User Text Field
        String id = (String) model.getValueAt(i, 0);
        tfIdUser.setText(id);
        // Menambahkan Text Ke Username Text Field
        String user = (String) model.getValueAt(i, 1);
        tfUsername.setText(user);
        // Method UNtuk Mengisi Password ke Password Password Field
        EdtPassword();
        // Menambakan Text Ke Nama Lengkap  Text Field
        String namaa = (String) model.getValueAt(i, 2);
        tfNamaLengkap.setText(namaa);
        // Seleksi Jenis Kelamin Berdasarkan Data 
        String jk = (String) model.getValueAt(i, 3);
        String l ="Laki-Laki";
        if(jk.equals(l)){
            rbLakiLaki.setSelected(true);
        }else{
            rbPerempuan.setSelected(true);
        }
        // Menambakan Text Ke No Telepon  Text Field
        String notelpp = (String) model.getValueAt(i, 4);
        tfNoTelp.setText(notelpp);
        // Menambakan Text Ke Alamat  Text Field
        String alamatt = (String) model.getValueAt(i, 5);
        taAlamat.setText(alamatt);
    }//GEN-LAST:event_tblAdminMouseClicked

    // Method Untuk Kembali Ke Form Menu
    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        Form_Menu au = new Form_Menu();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed

    // Method Untuk Membersihkan Form
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgClear;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbIdUser;
    private javax.swing.JLabel lbJenisKelamin;
    private javax.swing.JLabel lbNamaLengkap;
    private javax.swing.JLabel lbNoTelp;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JRadioButton rbLakiLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTextField tfIdUser;
    private javax.swing.JTextField tfNamaLengkap;
    private javax.swing.JTextField tfNoTelp;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
