/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AplikasiPenjualan;

import javax.swing.JOptionPane;

/**
 *
 * @author Pradana
 */

public class Form_Login extends javax.swing.JFrame {

    /**
     * Creates new form Form_Login
     */
    
    public Form_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnMasuk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbUsername.setText("Username");
        jPanel1.add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 20));

        lbPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPassword.setText("Password");
        jPanel1.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 20));
        jPanel1.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 230, 30));
        jPanel1.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 230, 30));

        btnMasuk.setText("Masuk");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        jPanel1.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        lbTitle.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("APLIKASI PENJUALAN TOKO KOMPUTER");
        jPanel2.add(lbTitle);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        String username = tfUsername.getText();
        String password = pfPassword.getText();
        String id_user_l = null, username_l = null, password_l = null;
        // Validasi Data Harus Terisi
        if(tfUsername.getText().equals("") && pfPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Username Dan Password Kosong");
        } else {
        try {
            // Koneksi Ke Database
            java.sql.Connection conn = (java.sql.Connection) koneksi.getKoneksi();
            // Queri Mendapatkan Data Tabel Admin
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select id_user, username, password from tbl_admin where username='" + tfUsername.getText() + "' and password = '" + pfPassword.getText() + "'");
            // Mendapatkan Data dan Menyimpan Ke Sesi
            while (sql.next()) {
                id_user_l = sql.getString("id_user");
                username_l = sql.getString("username");
                password_l = sql.getString("password");
            }
            sql.last();
            // Validasi Login
            if (sql.getRow()==1){
                Sesi.setId_user_log(id_user_l);
                Sesi.setUsername_log(username_l);
                Sesi.setPassword_log(password_l);     
                JOptionPane.showMessageDialog(null, "Login Berhasil");
                new Form_Menu().setVisible(true);
                this.dispose();
            } else {
            // Validasi Jika User Tidak Tersedia
                JOptionPane.showMessageDialog(null, "Maaf, Username / Password Salah!!!");
                tfUsername.setText("");
                pfPassword.setText("");
                pfPassword.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Form");
        }
       }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Konfirmasi Keluar?", "Pesan", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                 this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnMasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasuk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
